spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          #git仓库 在公司里，配置存储仓库  单独的https://github.com/zhanghwei/zhangwei-springcloud.git
          uri: https://github.com/zhanghwei/zhangwei-springcloud.git
            #检索目录
          search-paths:
            - configfiles
          #默认拉取的配置分支
          default-label: master
            #从那个分支去拉取配置文件
        label: spring-cloud-config
server:
  port: 8888
  servlet:
    context-path: /config/

eureka:
  client:
    service-uri:
      defaultZone: http://localhost:8761/eureka/